### ISSUE TITLE
DBAuth object has no attribute 'session'

### ISSUE THREAD

**Issue by ghost** [galeo/web.py-auth#2]
Hi!

I've trying to test the demo in this module and I have the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/local/lib/python2.7/dist-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python2.7/dist-packages/web.py-0.37-py2.7.egg/web/application.py", line 405, in _delegate
    return handle_class(f)
  File "/usr/local/lib/python2.7/dist-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "../auth/handlers.py", line 52, in GET
    if 'user' in auth.session.keys():
AttributeError: 'DBAuth' object has no attribute 'session'

Am I doing something wrong?

Thank you very much! :)
Vanessa

**Comment by galeo** [comment]
Hi, @vpena 
The demo app is outdated after the previous refactoring. It should be OK since aa5edd6.

Thank you for the catch.

**Comment by ghost** [comment]
Thank you so much! :D
